Added pdiff command

diff --git a/bin/pmgadmin b/bin/pmgadmin
--- a/bin/pmgadmin
+++ b/bin/pmgadmin
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck disable=2034
 # shellcheck disable=1090
+# shellcheck disable=2317
 #---------------------------------------------------------------------
 #
 #  pmgadmin_new
@@ -38,39 +39,39 @@ set -o pipefail
 #---------------------------------------------------------------------
 bpUserSettings() {
 
-#  UID    UNAME NAME             EMAIL                     SHELL
-userList=(                      \
-  "2000" "pmg"  "Peter Malmberg" "peter.malmberg@gmail.com" "/bin/bash" \
-	"2001" "tpmg" "Peter Malmberg" "peter.malmberg@gmail.com" "/bin/bash" \
-)
+  #  UID    UNAME NAME             EMAIL                     SHELL
+  userList=(
+    "2000" "pmg" "Peter Malmberg" "peter.malmberg@gmail.com" "/bin/bash"
+    "2001" "tpmg" "Peter Malmberg" "peter.malmberg@gmail.com" "/bin/bash"
+  )
 
-userList_test=(                      \
-  "5000" "apmg" "APeter Malmberg" "apeter.malmberg@gmail.com" "/bin/bash" \
-  "5001" "bpmg" "BPeter Malmberg" "bpeter.malmberg@gmail.com" "/bin/bash" \
-	"5002" "cpmg" "CPeter Malmberg" "cpeter.malmberg@gmail.com" "/bin/bash" \
-	"5003" "dpmg" "DPeter Malmberg" "dpeter.malmberg@gmail.com" "/bin/bash" \
-)
+  userList_test=(
+    "5000" "apmg" "APeter Malmberg" "apeter.malmberg@gmail.com" "/bin/bash"
+    "5001" "bpmg" "BPeter Malmberg" "bpeter.malmberg@gmail.com" "/bin/bash"
+    "5002" "cpmg" "CPeter Malmberg" "cpeter.malmberg@gmail.com" "/bin/bash"
+    "5003" "dpmg" "DPeter Malmberg" "dpeter.malmberg@gmail.com" "/bin/bash"
+  )
 
-# GROUPID  GROUPNAME
-groupList=(
-)
+  # GROUPID  GROUPNAME
+  groupList=(
+  )
 
-groupList_test=(
-  "10002" "groupname1" \
-  "10003" "groupname2" \
-)
+  groupList_test=(
+    "10002" "groupname1"
+    "10003" "groupname2"
+  )
 
-#  USER   GROUP
-userGroup=( \
-  "lpmg" "dialout" \
-	"pmg"  "dialout" \
-	"pmg" "adm" \
-	"pmg" "sudo" \
-)
+  #  USER   GROUP
+  userGroup=(
+    "lpmg" "dialout"
+    "pmg" "dialout"
+    "pmg" "adm"
+    "pmg" "sudo"
+  )
 
-RPSERVER=rpserver
-RPSERVER_SHARE=${RPSERVER}:\Files
-RPSERVER_MNT=/mnt/rpserver
+  RPSERVER=rpserver
+  RPSERVER_SHARE=${RPSERVER}:\files
+  RPSERVER_MNT=/mnt/rpfiles
 
 }
 #---------------------------------------------------------------------
@@ -81,34 +82,45 @@ RPSERVER_MNT=/mnt/rpserver
 # Create dir if it does not exist
 # $1 directory to be created
 #
-cDir() {
-  if [ ! -d "$1" ]; then
-    mkdir -p $1
-  fi
-}
+# cDir() {
+#   if [ ! -d "$1" ]; then
+#     mkdir -p $1
+#   fi
+# }
 
 ##- Filesystems
 
-mountServer() {  ##D Add mount rule to fileserver in fstab
+mountServer() { ##D Add mount rule to fileserver in fstab
   bpAssertRoot
   cDir /storage
-  appendIfNoSuchLine /etc/fstab  "fileserver:/storage  /storage nfs    auto   0 0"
+  bpAppendIfNoSuchLine /etc/fstab "fileserver:/storage  /storage nfs    auto   0 0"
 }
 
+nfs_mount() { ##I Mount nfs share
+  SHARE="$1"
+  MPOINT="$2"
+  #sudo bpMkDir "$MPOINT"
+}
+
+bpSudo=false
 
 mrps() { ##D Mount rpserver nfs share
-  sudo mkdir -p ${RPSERVER_MNT}
-  if sudo mount -t nfs ${RPSERVER_SHARE}  $RPSERVER_MNT ; then
-	  bpOk "Rpserver mounted on ${RPSERVER_MNT}"
-	else
-	  bpError "Failed to mount rpserver nfs share"
-	fi 
+
+  bpSudo=true
+  bpMkDir "${RPSERVER_MNT}"
+  bpSudo=false
+  #if sudo mount -t nfs ${RPSERVER_SHARE}  $RPSERVER_MNT ; then
+  #  bpOk "Rpserver mounted on ${RPSERVER_MNT}"
+  #else
+  #  bpError "Failed to mount rpserver nfs share"
+  #fi
 }
 
-addrps() {  ##D Add mount rule to rpserver in fstab
-#  bpAssertRoot
-  cDir /storage
-  appendIfNoSuchLine /etc/fstab  "${RPSERVER_SHARE}  ${RPSERVER_MNT} nfs    auto   0 0"
+addrps() { ##D Add mount rule to rpserver in fstab
+  bpSudo=true
+  bpMkDir "${RPSERVER_MNT}"
+  bpAppendIfNoSuchLine /etc/fstab "${RPSERVER_SHARE}  ${RPSERVER_MNT} nfs    auto   0 0"
+  bpSudo=false
 }
 
 ##- Users & groups
@@ -117,26 +129,25 @@ addSambaUser() {
   smbpasswd -a pmg
 }
 
-# 
+#
 # Check if user exists
 #
 # $1 uid
 #
-bpIsUser() { 
-  getent passwd $1 > /dev/null
-	return $?
+bpIsUser() {
+  getent passwd $1 >/dev/null
+  return $?
 }
 
-# 
+#
 # Check if group exists
 #
 # $1 uid
 #
-bpIsGroup() { 
-  getent group $1 > /dev/null
-	return $?
+bpIsGroup() {
+  getent group $1 >/dev/null
+  return $?
 }
-
 
 #
 # Add a new user if not existing
@@ -147,37 +158,37 @@ bpIsGroup() {
 # $4 = email
 # $5 = shell
 #
-addUser() { 
-	if bpIsUser $2; then
-  	bpInfo "User "$2" already exists"
-		return
+addUser() {
+  if bpIsUser $2; then
+    bpInfo "User "$2" already exists"
+    return
   fi
-	
-	if sudo useradd "$1" --create-home --uid "$2" --shell "$5" --comment "${3},,,"; then
-	  bpOk "Adding user:  $1 $2 $3 $4"
-	else
-	  bpError "Failed to add user $1"
-	fi
-  
+
+  if sudo useradd "$1" --create-home --uid "$2" --shell "$5" --comment "${3},,,"; then
+    bpOk "Adding user:  $1 $2 $3 $4"
+  else
+    bpError "Failed to add user $1"
+  fi
+
 }
 
 #
 # Add group
-# 
+#
 # $1 = group
 # $2 = id
 #
 addGroup() {
   if bpIsGroup $1; then
-	  bpInfo "Group $1 already exists"
-		return 1;
-	fi
-    
+    bpInfo "Group $1 already exists"
+    return 1
+  fi
+
   if sudo groupadd $1 --gid $2; then
-  	bpOk "Adding group: "$1
-	else
-	  bpError "Failed adding group $1"
-	fi
+    bpOk "Adding group: "$1
+  else
+    bpError "Failed adding group $1"
+  fi
 }
 
 #
@@ -186,16 +197,16 @@ addGroup() {
 # $1 = username
 # $2 = userid
 #
-rmUser() {  
+rmUser() {
   if ! bpIsUser $2; then
-		bpError "User "$1" does not exist"
-		return
+    bpError "User "$1" does not exist"
+    return
   fi
-	
-	if sudo deluser $1 --remove-home &> /dev/null; then
-	  bpOk "Removed user:  $1"
-	else
-	  bpError "Failed to remove user $1"
+
+  if sudo deluser $1 --remove-home &>/dev/null; then
+    bpOk "Removed user:  $1"
+  else
+    bpError "Failed to remove user $1"
   fi
 }
 
@@ -205,147 +216,140 @@ rmUser() {
 # $1 = group
 #
 rmGroup() {
-  if ! bpIsGroup $1; then
-	  bpError "Group "$1" does not exist"
-		return
+  if ! bpIsGroup "$1"; then
+    bpError "Group $1 does not exist"
+    return
   fi
-  
-  if sudo delgroup $1 &> /dev/null; then
- 	  bpOk "Removing group:  $1"
-	else
-	  bpError "Failed at removing group $1"
-	fi
-}
 
+  if sudo delgroup "$1" &>/dev/null; then
+    bpOk "Removing group:  $1"
+  else
+    bpError "Failed at removing group $1"
+  fi
+}
 
 cug() { ##D Create users and groups
   cu
-	cg
+  cg
 }
-
 
 aug() { ##D Add users to groups
-	i=0
-	len=${#userGroup[@]}
-	while [ $i -lt $len ]; do
-	  USER=${userGroup[i]}
-		(( i++ ))
-		GROUP=${userGroup[i]}
-		(( i++ ))
-	  
-		if sudo usermod -a -G "$GROUP" "$USER"; then
-		  bpOk "Adding user $USER to group $GROUP"
-		else
-		  bpError "Failed adding user $USER to group $GROUP"
-		fi
-	done
-}
+  i=0
+  len=${#userGroup[@]}
+  while [ "$i" -lt "$len" ]; do
+    USER=${userGroup[i]}
+    ((i++))
+    GROUP=${userGroup[i]}
+    ((i++))
 
+    if sudo usermod -a -G "$GROUP" "$USER"; then
+      bpOk "Adding user $USER to group $GROUP"
+    else
+      bpError "Failed adding user $USER to group $GROUP"
+    fi
+  done
+}
 
 rug() { ##D Remove users and groups
   IFS=$'\n'
-	i=0
-	len=${#userList[@]}
-	while [ $i -lt $len ]; do
-	  UI=${userList[i]}
-		(( i++ ))
-		UN=${userList[i]}
-		(( i++ ))
-		US=${userList[i]}
-		(( i++ ))
-		UE=${userList[i]}
-		(( i++ ))
-		(( i++ ))
-		rmUser "$UN" "$UI"
-	done
+  i=0
+  len=${#userList[@]}
+  while [ "$i" -lt "$len" ]; do
+    UI=${userList[i]}
+    ((i++))
+    UN=${userList[i]}
+    ((i++))
+    US=${userList[i]}
+    ((i++))
+    UE=${userList[i]}
+    ((i++))
+    ((i++))
+    rmUser "$UN" "$UI"
+  done
 
   i=0
-	len=${#groupList[@]}
-	while [ $i -lt $len ]; do
-	  G_ID=${groupList[i]}  
-		(( i++ ))
+  len=${#groupList[@]}
+  while [ "$i" -lt "$len" ]; do
+    G_ID=${groupList[i]}
+    ((i++))
     G_NAME=${groupList[i]}
-		(( i++ ))
+    ((i++))
     rmGroup "${G_NAME}"
   done
 }
 
-
 omv() { ##D Open media vault import data
   IFS=$'\n'
-	bpPrintLine Users
-	echo
-	i=0
-	len=${#userList[@]}
-	while [ $i -lt $len ]; do
-	  U_ID=${userList[i]}
-		(( i++ ))
-		U_NAME=${userList[i]}
-		(( i++ ))
-		U_PERSONAL=${userList[i]}
-		(( i++ ))
-		U_EMAIL=${userList[i]}
-		(( i++ ))
-		U_SHELL=${userList[i]}
-		(( i++ ))	
-		# <username>;<uid>;<comment>;<email>;<password>;<shell>;<groupname,groupname,...>;<disallowusermod>
-		echo "${U_NAME};${U_ID};${U_PERSONAL};${U_EMAIL};;${U_SHELL};;false"
-	done
-	
-	echo
-	bpPrintLine Groups
-	echo
-	i=0
-	len=${#groupList[@]}
-	while [ $i -lt $len ]; do
-	  G_ID=${groupList[i]}
-		(( i++ ))
-		G_NAME=${groupList[i]}
-		(( i++ ))
-		echo "${G_NAME};${G_ID};"
-	done								
-}
+  bpPrintLine Users
+  echo
+  i=0
+  len=${#userList[@]}
+  while [ "$i" -lt "$len" ]; do
+    U_ID=${userList[i]}
+    ((i++))
+    U_NAME=${userList[i]}
+    ((i++))
+    U_PERSONAL=${userList[i]}
+    ((i++))
+    U_EMAIL=${userList[i]}
+    ((i++))
+    U_SHELL=${userList[i]}
+    ((i++))
+    # <username>;<uid>;<comment>;<email>;<password>;<shell>;<groupname,groupname,...>;<disallowusermod>
+    echo "${U_NAME};${U_ID};${U_PERSONAL};${U_EMAIL};;${U_SHELL};;false"
+  done
 
+  echo
+  bpPrintLine Groups
+  echo
+  i=0
+  len=${#groupList[@]}
+  while [ "$i" -lt "$len" ]; do
+    G_ID=${groupList[i]}
+    ((i++))
+    G_NAME=${groupList[i]}
+    ((i++))
+    echo "${G_NAME};${G_ID};"
+  done
+}
 
 cu() { ##D Create users
   IFS=$'\n'
-	i=0
-	len=${#userList[@]}
-	while [ $i -lt $len ]; do
-	  U_ID=${userList[i]}
-		(( i++ ))
-		U_NAME=${userList[i]}
-		(( i++ ))
-		U_PERSONAL=${userList[i]}
-		(( i++ ))
-		U_EMAIL=${userList[i]}
-		(( i++ ))
-		U_SHELL=${userList[i]}
-		(( i++ ))	
-		addUser "$U_NAME" "$U_ID" "$U_PERSONAL" "$U_SHELL" "$U_SHELL" 
-	done
+  i=0
+  len=${#userList[@]}
+  while [ "$i" -lt "$len" ]; do
+    U_ID=${userList[i]}
+    ((i++))
+    U_NAME=${userList[i]}
+    ((i++))
+    U_PERSONAL=${userList[i]}
+    ((i++))
+    U_EMAIL=${userList[i]}
+    ((i++))
+    U_SHELL=${userList[i]}
+    ((i++))
+    addUser "$U_NAME" "$U_ID" "$U_PERSONAL" "$U_SHELL" "$U_SHELL"
+  done
 }
-
 
 cg() { ##D Create groups
   IFS=$'\n'
   i=0
-	len=${#groupList[@]}
-	while [ $i -lt $len ]; do
-	  G_ID=${groupList[i]}  
-		(( i++ ))
+  len=${#groupList[@]}
+  while [ $i -lt $len ]; do
+    G_ID=${groupList[i]}
+    ((i++))
     G_NAME=${groupList[i]}
-		(( i++ ))
-    addGroup "$G_NAME" "$G_ID"   
+    ((i++))
+    addGroup "$G_NAME" "$G_ID"
   done
 }
 
 ##-
 
 addpath() { ##D Add path to PATH
-  bpAddPath $2
+  bpAddPath" $2"
 }
-
 
 #---------------------------------------------------------------------
 # Bashplate settings
@@ -653,7 +657,7 @@ bpPrintLine() { ##I Print text with line after
   fi
 }
 
-bpPrintLine_deprecated()  { ##I Print a divider row
+bpPrintLine_deprecated() { ##I Print a divider row
   bpPrintLineGeneric "" "${BP_C_LINE}" "${BP_C_LINE}" "" "-"
 }
 
@@ -758,12 +762,34 @@ bpHasCmd() { ##I Check if command is available
 #
 # $1 command to execute
 #
+# bpRun() { ##I Execute command
+#   if bpHasCmd "${1}"; then
+#     "$@"
+#     return $?
+#   else
+#     bpError "Could not execute $1, command does not exist!"
+#     return 1
+#   fi
+# }
+
+#
+# $1 command to execute
+#
 bpRun() { ##I Execute command
+  echo XX: "$@"
   if bpHasCmd "${1}"; then
-    "$@"
+    if [ "$bpSudo" == true ]; then
+      sudo "$@"
+    else
+      "$@"
+    fi
     return $?
   else
-    bpError "Could not execute $1, command does not exist!"
+    if [ "$bpSudo" == true ]; then
+      bpError "Could not execute \"sudo $1\", command does not exist!"
+    else
+      bpError "Could not execute \"$1\", command does not exist!"
+    fi
     return 1
   fi
 }
@@ -780,11 +806,11 @@ bpCd() { ##I Safe cd function (exits on fail)
 #
 bpMkDir() { ##I Create a directory if it does not exist
   if [ ! -d "$1" ]; then
-    if mkdir -p "$1"; then
-      bpOk "Creating directory $(bpColorizeFile "${1}")."
+    if bpRun mkdir -p "$1"; then
+      bpOk "Creating directory $(bpColorizeFile "$(realpath "${1}")")"
       return 0
     else
-      bpError "Failed to create directory $(bpColorizeFile "${1}")."
+      bpError "Failed to create directory $(bpColorizeFile "$(realpath "${1}")")."
       return 1
     fi
   fi
@@ -885,7 +911,11 @@ bpReplaceLine() { ##I Replace entire line matching pattern
 # $2 line to append
 #
 bpAppendIfNoSuchLine() { ##I Append a line if it does not exist in file
-  grep -q -F "$2" "$1" || echo "$2" >>"$1"
+  if [ "$bpSudo" == true ]; then
+    sudo grep -q -F "$2" "$1" || echo -e "\n$2" | sudo tee -a "$1"
+  else
+    grep -q -F "$2" "$1" || echo -e "\n$2" >>"$1"
+  fi
 }
 
 #
@@ -1545,7 +1575,6 @@ iinfo() { ##I Show information about script
   fi
   settings
 }
-
 
 iview() { ##I View example
   # Singe command documentation
